# app.yaml = application config file

version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fontawesome
  static_dir: fontawesome

- url: /stylesheet
  static_dir: stylesheet

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
