# app.yaml = application config file

version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fontawesome
  static_dir: fontawesome

<<<<<<< HEAD
- url: /bootstrap
  static_dir: bootstrap

- url: /resources
  static_dir: resources

- url: /stylesheet
  static_dir: stylesheet

- url: /javascript
  static_dir: javascript
=======
- url: /stylesheet
  static_dir: stylesheet

- url: /bootstrap
  static_dir: bootstrap
>>>>>>> 542908cfafd42156773d4f0751aa784c9e79c0a6

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
